FROM php:8.1-cli

ARG project_dir

SHELL ["/bin/bash", "--login", "-c"]

RUN apt-get update && \
    apt-get upgrade -y
RUN apt-get install -y git
RUN apt-get install -y openssh-client
RUN apt-get install -y sudo
RUN apt-get install -y vim

# php extensions
RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN apt-get install -y \
        libzip-dev \
        zip
RUN docker-php-ext-install -j$(nproc) zip

# composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv ${HOME}/.symfony5/bin /usr/local/bin/symfony
ENV PATH="/usr/local/bin/symfony:${PATH}"

COPY ./xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
RUN nvm install v18
RUN nvm alias default v18